### ISSUE TITLE
ios不越狱无法安装吗

### ISSUE THREAD

**Issue by han24132566** [mgfjxxiexiaolong/JAVBus#2]
ios不越狱无法安装吗

**Comment by mgfjxxiexiaolong** [comment]
是的。或者自己使用AltStore签名[小雷锋教你安装使用 AltStore](https://mp.weixin.qq.com/s?__biz=MzUyNjE1MzExMA==&mid=2247494323&idx=1&sn=ab30e86375492c62ac20dfe5dcc17e7d&chksm=fa118e4acd66075c62da2495685e62ba318c73b99b0df1459b528202707777f933d135e89bf2&scene=21#wechat_redirect)。
如果你是iOS开发者可以下载项目直接真机跑也能安装。
